CREATE TABLE tasks (
    task_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_task_id BIGINT,
    level          INTEGER                                 NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255)                            NOT NULL,
    priority       INTEGER,
    status         INTEGER,
    CONSTRAINT pk_tasks PRIMARY KEY (task_id)
);