DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS requirements;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users_roles;

CREATE TABLE IF NOT EXISTS projects
(
    project_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    description    VARCHAR(2048)                           NOT NULL,
    priority       INTEGER,
    status         SMALLINT,
    created_by_id  BIGINT                                  NOT NULL,
    assigned_to_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (project_id)
);

CREATE TABLE IF NOT EXISTS requirements
(
    step_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id        BIGINT,
    title          VARCHAR(255)                            NOT NULL,
    description    VARCHAR(2048)                           NOT NULL,
    status         SMALLINT,
    created_by_id  BIGINT                                  NOT NULL,
    assigned_to_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_requirements PRIMARY KEY (step_id)
);

CREATE TABLE IF NOT EXISTS roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS tasks
(
    task_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id     BIGINT,
    name           VARCHAR(255)                            NOT NULL,
    description    VARCHAR(2048)                           NOT NULL,
    priority       INTEGER,
    status         SMALLINT,
    created_by_id  BIGINT                                  NOT NULL,
    assigned_to_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tasks PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    enabled        BOOLEAN                                 NOT NULL,
    locked         BOOLEAN                                 NOT NULL,
    first_name     VARCHAR(255)                            NOT NULL,
    middle_name    VARCHAR(255),
    last_name      VARCHAR(255)                            NOT NULL,
    phone          VARCHAR(255),
    contact_method VARCHAR(255),
    manager_id     BIGINT,
    date_created   TIMESTAMP WITHOUT TIME ZONE,
    date_updated   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_ASSIGNED_TO FOREIGN KEY (assigned_to_id) REFERENCES users (user_id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (user_id);

ALTER TABLE requirements
    ADD CONSTRAINT FK_REQUIREMENTS_ON_ASSIGNED_TO FOREIGN KEY (assigned_to_id) REFERENCES users (user_id);

ALTER TABLE requirements
    ADD CONSTRAINT FK_REQUIREMENTS_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (user_id);

ALTER TABLE requirements
    ADD CONSTRAINT FK_REQUIREMENTS_ON_TASK FOREIGN KEY (task_id) REFERENCES tasks (task_id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ASSIGNED_TO FOREIGN KEY (assigned_to_id) REFERENCES users (user_id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (user_id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (project_id);

ALTER TABLE users_roles
    ADD CONSTRAINT FK_USERS_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE users_roles
    ADD CONSTRAINT FK_USERS_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);