spring:
  application:
    name: project-management-system
  datasource:
    url: jdbc:postgresql://localhost:32768/postgres
    username: postgres
  sql:
    init:
      mode: always

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always
  port: 80
