spring:
  application:
    name: project-management-system
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:32768/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always
  port: ${PORT:80}
